=== icdocsoc/mailgen/resources/email.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified">
  <xsd:annotation>
    <xsd:documentation xml:lang="en">
      DoCSoc Email Generator Schema.
    </xsd:documentation>
  </xsd:annotation>

  <xsd:element name="email" type="EmailType"/>

  <xsd:complexType name="EmailType">
    <xsd:choice maxOccurs="unbounded">
      <xsd:element name="heading" type="xsd:string" />
      <xsd:element name="text" type="xsd:string" />
      <xsd:element name="event" type="EventType" />
      <xsd:element name="sponsor" type="SponsorType" />
      <xsd:element name="image" type="ImageType" />
      <xsd:element name="sign" type="SignType" />
      <xsd:element name="hr" type="xsd:NMTOKENS" />
    </xsd:choice>
    <xsd:attribute name="logos" type="xsd:boolean" default="true" />
    <xsd:attribute name="agenda" type="xsd:boolean" default="true" />
    <xsd:attribute name="social" type="xsd:boolean" default="true" />
    <xsd:attribute name="title" type="xsd:string" />
  </xsd:complexType>

  <xsd:complexType name="EventType">
    <xsd:all>
      <xsd:element name="image" minOccurs="0">
        <xsd:complexType>
          <xsd:attribute name="src" type="xsd:anyURI" use="required" />
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="facebook" minOccurs="0">
        <xsd:complexType>
          <xsd:attribute name="id" type="xsd:nonNegativeInteger" use="required" />
          <xsd:attribute name="alias" type="xsd:anyURI" />
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="links" minOccurs="0">
        <xsd:complexType>
          <xsd:sequence maxOccurs="unbounded">
            <xsd:element name="link">
              <xsd:complexType>
                <xsd:simpleContent>
                  <xsd:extension base="xsd:string">
                    <xsd:attribute name="href" type="xsd:anyURI" use="required" />
                  </xsd:extension>
                </xsd:simpleContent>
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="text" type="xsd:string" minOccurs="0" />
    </xsd:all>

    <xsd:attribute name="startDate" type="xsd:dateTime" default="1970-01-01T00:00:00Z" />
    <xsd:attribute name="endDate" type="xsd:dateTime" default="1970-01-01T00:00:00Z" />
    <xsd:attribute name="location" type="xsd:string" />
    <xsd:attribute name="external" type="xsd:boolean" default="false" />
  </xsd:complexType>

  <xsd:complexType name="SponsorType">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="company" use="required">
          <xsd:simpleType>
            <xsd:restriction base="xsd:string">
              <xsd:enumeration value="wluper" />
              <xsd:enumeration value="amex" />
              <xsd:enumeration value="arrival" />
              <xsd:enumeration value="artificiallabs" />
              <xsd:enumeration value="baml" />
              <xsd:enumeration value="blackrock" />
              <xsd:enumeration value="bloomberg" />
              <xsd:enumeration value="citadel" />
              <xsd:enumeration value="crowdstrike" />
              <xsd:enumeration value="drw" />
              <xsd:enumeration value="ef" />
              <xsd:enumeration value="facebook" />
              <xsd:enumeration value="g_research" />
              <xsd:enumeration value="go_cardless" />
              <xsd:enumeration value="gousto" />
              <xsd:enumeration value="graphcore" />
              <xsd:enumeration value="imc" />
              <xsd:enumeration value="jane_street" />
              <xsd:enumeration value="jpmorgan" />
              <xsd:enumeration value="jump_trading" />
              <xsd:enumeration value="liquidnet" />
              <xsd:enumeration value="lseg" />
              <xsd:enumeration value="macquarie" />
              <xsd:enumeration value="microsoft" />
              <xsd:enumeration value="netcraft" />
              <xsd:enumeration value="next_jump" />
              <xsd:enumeration value="optiver" />
              <xsd:enumeration value="oliver_wyman" />
              <xsd:enumeration value="palantir" />
              <xsd:enumeration value="pdtpartners" />
              <xsd:enumeration value="samsungrd" />
              <xsd:enumeration value="schlumberger" />
              <xsd:enumeration value="showcode" />
              <xsd:enumeration value="stakezero" />
              <xsd:enumeration value="starleaf" />
              <xsd:enumeration value="thought_machine" />
              <xsd:enumeration value="twosigma" />
              <xsd:enumeration value="vmware" />
              <xsd:enumeration value="wluper" />
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:attribute>
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>

  <xsd:complexType name="ImageType">
    <xsd:attribute name="width" type="xsd:nonNegativeInteger" default="100" />
    <xsd:attribute name="src" type="xsd:anyURI" use="required" />
    <xsd:attribute name="alt" type="xsd:string" />
    <xsd:attribute name="title" type="xsd:string" />
    <xsd:attribute name="link" type="xsd:string" />
  </xsd:complexType>

  <xsd:complexType name="SignType">
    <xsd:simpleContent>
      <xsd:extension base="xsd:string">
        <xsd:attribute name="name" type="xsd:string" use="required" />
        <xsd:attribute name="role" type="xsd:string" use="required" />
        <xsd:attribute name="facebook" type="xsd:string" />
        <xsd:attribute name="linkedin" type="xsd:string" />
      </xsd:extension>
    </xsd:simpleContent>
  </xsd:complexType>
</xsd:schema>

=== icdocsoc/mailgen/examples/test.xml
<?xml version="1.0" encoding="UTF-8" ?>
<email xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://docsoc.co.uk/xml/email email.xsd"
  logos="true" agenda="true" social="true" title="Weekly Digest">
  <heading>
    Something
  </heading>
  <text>
    Verbatim text
  </text>

  <heading>Next Jump Christmas Bar Night (manual link &amp; location)</heading>
  <event location="Metric">
    <facebook id="137844650270705" alias="http://docsoc.co.uk/christmas-bar-night" />
    <links>
      <link href="link">Not Facebook</link>
    </links>
  </event>

  <heading>
    Next Jump Christmas Bar Night (automatic)
  </heading>
  <event>
    <facebook id="137844650270705" />
  </event>

  <heading>AlphaGo</heading>
  <event external="true">
    <facebook id="787130688161502" />
    <text>
      I want custom text
    </text>
  </event>

  <text>
    *But this is markdown right*
  </text>

  <hr/>
  <hr/>
  <hr/>

  <sponsor company="bloomberg">
    Sponsor post
  </sponsor>

  <image width="100" src="link to image" alt="alt text" title="title" />

  <sign name="Nik Vangerow"
    role="DoCSoc Secretary"
    facebook="nik.vangerow">
    That's all for now!

    Until next time,
  </sign>
</email>
